<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>KML Click Capture Sample</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="w3_edited.css">
    <script type='text/javascript' src='over_map.js'></script>

  </head>
  <body>

    <div id="over_map">
    <div class="w3-opennav w3-xlarge w3-hide-xlarge w3-right" onclick="w3_open()">&#9776;</div>
    <nav class="w3-sidenav w3-collapse w3-white w3-card-2 w3-animate-right" style="width:0px;right:0;" id="mySidenav">

      <a href="javascript:void(0)" onclick="w3_close()" class="w3-closenav w3-xlarge w3-hide-xlarge">&times;</a>
      <h1 style="text-align:center;font-size: 24px;">Station 4:</h1>
      <h2 style="text-align:center;font-size: 18px;">Wheel Alignment</h2>
      <p>    </p>
      <?php
      include('../back_end/hostTest.php');
      //$arr = json_decode($myJsonObject, true);
      echo $myJsonObject;
      ?>








      <!-- Each of these "buttons" will be generated by a script that
        runs through the list of hosts and collects their info -->
      <buttonRed class="accordion">Device 5</buttonRed>
      <div class="panel">
        <!-- Here we will have the actual status, etc for each device
                <a href="#">Device 5</a> -->
        <p>Status: disconnected</p>
        <p>IP Address: 102.50.103.101</p>
        <p>Name: Arduino Uno</p>
        <img id="device" src="device_images/arduino.png" alt="Arduino"></img>
        <p>  </p>
      </div>

      <buttonRed class="accordion">Device 9</buttonRed>
      <div class="panel">
        <p>Status: paper jam</p>
        <p>IP Address: 104.58.183.103</p>
        <p>Name: HP Color Laserjet Pro</p>
        <img id="device" src="device_images/printer.png" alt="Printer"></img>
        <p>  </p>
      </div>

      <buttonYellow class="accordion">Device 8</buttonYellow>
      <div class="panel">
        <p>Device info can go here.</p>
      </div>

      <buttonYellow class="accordion">Device 1</buttonYellow>
      <div class="panel">
        <p>Status: CPU at 98% capacity</p>
        <p>IP Address: 189.23.33.100</p>
        <p>Name: Dell XPS Developer</p>
        <img id="device" src="device_images/laptop.png" alt="Laptop"></img>
        <p>  </p>
      </div>

      <buttonYellow class="accordion">Device 6</buttonYellow>
      <div class="panel">
        <p>Device info can go here.</p>
      </div>

      <buttonGreen class="accordion">Device 21</buttonGreen>
      <div class="panel">
        <?php echo "hello" ?>
        <p>Status: 12 jobs in queue</p>
        <p>IP Address: 133.13.50.987</p>
        <p>Name: Canon Maxify MB2720</p>
        <img id="device" src="device_images/multifunction_printer.jpeg" alt="Multi_printer"></img>
        <p>  </p>
      </div>

      </div>
    </nav>
  </div>

    <div id="map">
      <div id="capture"></div>
    </div>
    <script type='text/javascript' src='over_map.js'></script>
    <script type='text/javascript' src='config.js'></script>
    <script type='text/javascript' src='geoxml3.js'></script>
    <script type='text/javascript' src='dashboard_map.js'></script>
    <script src="jquery-3.1.1.min.js"></script>   <!-- include jquery library -->

  </body>
</html>
